using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using RESERBA_Proj.Database;

namespace RESERBA_Proj
{
    public partial class SlotButton : UserControl
    {
        // 1. Setup gate array 
        private string[] gates = { "Gate 1", "Gate 2", "Gate 3" };
        private int currentGateIndex = 0;

        public SlotButton()
        {
            InitializeComponent();
            // Trigger the display update as soon as the control loads
            this.Load += SlotButton_Load;
        }

        private void SlotButton_Load(object sender, EventArgs e)
        {
            UpdateGateDisplay();
        }

        // 2. Fetch both Total and Available counts, then update the UI
        private void UpdateGateDisplay()
        {
            string currentGate = gates[currentGateIndex];
            int totalSlots = 0;
            int availableSlots = 0;

            try
            {
                using (var conn = DatabaseHelper.GetConnection())
                {
                    conn.Open();

                    // Query asks for the total count, and the count of only unoccupied slots
                    string query = "SELECT " +
                                   "COUNT(*) as Total, " +
                                   "SUM(CASE WHEN is_occupied = FALSE THEN 1 ELSE 0 END) as Available " +
                                   "FROM parking_slots WHERE gate_id = @gate";

                    var cmd = new MySqlCommand(query, conn);
                    cmd.Parameters.AddWithValue("@gate", currentGate);

                    using (var reader = cmd.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            // Safely parse the results from the database
                            totalSlots = reader["Total"] != DBNull.Value ? Convert.ToInt32(reader["Total"]) : 0;
                            availableSlots = reader["Available"] != DBNull.Value ? Convert.ToInt32(reader["Available"]) : 0;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error fetching gate stats: " + ex.Message);
            }

            // 3. Update both labels independently

            // Top Left Label (Gate Name)
            label2.Text = currentGate.ToLower();

            // Center Label (Available / Total)
            guna2HtmlLabel1.Text = $"{availableSlots}/{totalSlots}";
        }

        // 4. Arrow Click Events
        // (Make sure to double-click  right arrow in the designer and paste this inside!)


        // (Make sure to double-click left arrow in the designer and paste this inside!)


        // Empty stubs generated by the designer
        private void label2_Click(object sender, EventArgs e)
        {
        }

        private void guna2HtmlLabel1_Click(object sender, EventArgs e)
        {
        }

        private void BtnNext_Click(object sender, EventArgs e)
        {

            currentGateIndex++;
            if (currentGateIndex >= gates.Length)
            {
                currentGateIndex = 0;
            }
            UpdateGateDisplay();
        }

        private void panelSlot_Paint(object sender, PaintEventArgs e)
        {

        }

        private void BtnPrev_Click(object sender, EventArgs e)
        {
            currentGateIndex--;
            if (currentGateIndex < 0)
            {
                currentGateIndex = gates.Length - 1; // Loop to the end
            }
            UpdateGateDisplay();
        }
    }
}